# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdventGame < Formula
  desc "A CLI advent calendar: one puzzle a day, one letter per solve."
  homepage "https://github.com/itskbs/advent-game"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itskbs/advent-game/releases/download/v0.1.0/advent-game_darwin_amd64.tar.gz"
      sha256 "1cd171ca66baca1d9cda2fdcff354a1c4436131536d4dd050ffcca62360b06a1"

      define_method(:install) do
        bin.install "advent-game"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itskbs/advent-game/releases/download/v0.1.0/advent-game_darwin_arm64.tar.gz"
      sha256 "86383c12b830217499063fb26c6f672b0ba88982a287a5d0ca04589f85045658"

      define_method(:install) do
        bin.install "advent-game"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itskbs/advent-game/releases/download/v0.1.0/advent-game_linux_amd64.tar.gz"
      sha256 "bfa3e256e6db53b7670561c21c84a5db2df98da14b438ccd9c15aeb33b676b9b"
      define_method(:install) do
        bin.install "advent-game"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itskbs/advent-game/releases/download/v0.1.0/advent-game_linux_arm64.tar.gz"
      sha256 "d6f03e1c2115a7b9b01814832e21b2dff05e10c7b8d8412a99c97bf4fa248878"
      define_method(:install) do
        bin.install "advent-game"
      end
    end
  end

  test do
    system "#{bin}/advent-game", "help"
  end
end
